# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Guide to Allyship
email: guidetoallyship@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Guide to Allyship is an open-source guide for anyone who is
  interested in becoming an ally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.guidetoallyship.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
